# Generated by Django 3.2.16 on 2022-10-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221028_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='photos/tandaslogodashboard.png', upload_to='photos/'),
        ),
    ]
