# Generated by Django 3.2.16 on 2022-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Emp_Id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Team_Name',
            field=models.CharField(blank=True, choices=[('Team1', 'Team1'), ('Team2', 'Team2'), ('Team3', 'Team3')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Team_Type',
            field=models.CharField(blank=True, choices=[('Frames', 'Frames'), ('Doors', 'Doors')], max_length=10, null=True),
        ),
    ]
